#!/usr/bin/env bash

# Version: 		20170812-01
# Description:	Compress pdf files via nautilius context menue

set -euo pipefail
# -e: exit immidiately when a command fails. If piped check only the last command error code.
#     Use ||true for commands allowed to fail.
# -u: treat unset variable as an error and exit immidiately
# -o pipefail: same as -e but for all commands in a pipe.
# -x: debug option

# package required: ghostscript

# Check if required packages are installed
if ! which ps2pdf > /dev/null; then
  zenity --question --text="Command failed!\n\nA required package is missing. Try to install?" --ok-label="Yes" --cancel-label="No"
  if [ $? = 0 ] ; then
    gnome-terminal -x bash -c "echo sudo dnf install ghostscript && sudo dnf install ghostscript"
  else
    exit
  fi
fi

(
m=0 # counter
IFS="
"
# get number of files
for ARG in ${NAUTILUS_SCRIPT_SELECTED_FILE_PATHS}
  do
    if [[ ${ARG} == *.pdf ]]; then
      m=$(("${m}" + 1))
   else
     notify-send "Skipping: $(basename "${ARG}")"
   fi
done
percent=$((100 / "${m}"))

# process all files
m=0

percent_loop=0
for ARG in ${NAUTILUS_SCRIPT_SELECTED_FILE_PATHS}
  do
    if [[ "${ARG}" == *.pdf ]]; then
      ps2pdf  "${ARG}" "$(dirname "${ARG}")"/"$(basename "${ARG}" | sed 's/\.pdf/\_compress\.pdf/g')" 
      percent_loop=$(("${percent_loop}"+"${percent}"))
      echo "${percent_loop}"
      echo "# Done: $(basename "${ARG}")"
      m=$(("${m}" + 1))
   fi
done ) | zenity --progress \
  --title="PDF Compress" \
  --text="Analyzing files..." \
  --percentage=0