#!/bin/bash

for file in $NAUTILUS_SCRIPT_SELECTED_FILE_PATHS; do

if [[ -d "$file" ]]; then
exit
fi

  filename=$(echo $file | sed -e 's/.*\///g')
  arg=`echo $arg $filename`

done

Sumname=`zenity --entry --title="Make SFV $arg" --entry-text "checksum" --text="Insert desired name for the checksum file"`
if [ "$?" == 1 ] ; then echo ; fi

#zenity --info --title="Cksfv" --text="cksfv $arg > $Sumname.sfv"

(cksfv $arg > "$Sumname.sfv") 2>&1 | zenity --progress --title "Make SFV" --text "Making..." --pulsate --auto-close;

