#!/bin/bash

if [ ! -z $1 ]; then
  if [ -f $1 ] ; then
    echo "Extracting archive $1"
    case $1 in
    *.aes)      aes -d $1 ;;
    *.rpm)      checkpackage rpm2cpio && mkdir $(echo $1 | sed 's/\.rpm//g') && cp $1 $(echo $1 | sed 's/\.rpm//g')/ && cd $(echo $1 | sed 's/\.rpm//g')/ && (rpm2cpio $1 | cpio -i --make-directories) && rm $1 && cd ..       ;;
    *.deb)      checkpackage ar && mkdir $(echo $1 | sed 's/\.deb//g') && cp $1 $(echo $1 | sed 's/\.deb//g')/ && cd $(echo $1 | sed 's/\.deb//g')/ && ar vx $1 && rm $1 && extract control.tar.* && rm control.tar.* && extract data.tar.* && rm data.tar.* && cd ..       ;;
    *.tar.bz2)      tar xjf $1      ;;
    *.tar.gz)       tar xzf $1      ;;
    *.tar.xz)       checkpackage xz xz-utils && tar xJf $1      ;;
    *.bz2)  checkpackage bzip2 && bunzip2 $1      ;;
    *.rar)  rar x $1;;
    *.gz)   gunzip $1       ;;
    *.tar)  tar xf $1       ;;
    *.tbz2) tar xjf $1      ;;
    *.tgz)  tar xzf $1      ;;
    *.zip)  checkpackage unzip && unzip $1;;
    *.7z)   checkpackage 7z p7zip-full && folder=$(echo $1 | sed 's/\.7z//g') && mkdir ${folder} && mv $1 ${folder} && cd ${folder} && 7z e $1 ;;
    *.Z)    checkpackage ncompress && uncompress $1   ;;
    *)      echo "'$1' cannot be extracted via extract()" ;;
    esac
  else
    echo "'$1' is not a valid file"
  fi
else
  echo "Usage: $(basename $0) {file to extract}"
fi
