#!/bin/bash

  if [ ! -z $1 ]; then
    if [ -f $1 ] ; then
      echo "Extracting archive $1"
      case $1 in
      *.tar.bz2)      tar xjf $1      ;;
      *.tar.gz)       tar xzf $1      ;;
      *.tar.xz)       tar xJf $1      ;;
      *.bz2)  checkpackage bzip2 && bunzip2 $1      ;;
      *.rar)  rar x $1;;
      *.gz)   gunzip $1       ;;
      *.tar)  tar xf $1       ;;
      *.tbz2) tar xjf $1      ;;
      *.tgz)  tar xzf $1      ;;
      *.zip)  checkpackage unzip && unzip $1;;
      *.Z)    checkpackage ncompress && uncompress $1   ;;
      *)      echo "'$1' cannot be extracted via extract()" ;;
      esac
    else
      echo "'$1' is not a valid file"
    fi
  fi
