#!/bin/bash

function highlight() {
        declare -A fg_color_map
        fg_color_map[black]=30
        fg_color_map[red]=31
        fg_color_map[green]=32
        fg_color_map[yellow]=33
        fg_color_map[blue]=34
        fg_color_map[magenta]=35
        fg_color_map[cyan]=36

        fg_c=$(echo -e "\e[1;${fg_color_map[$1]}m")
        c_rs=$'\e[0m'
        sed s"/$2/$fg_c\0$c_rs/"
}

ps aux | grep "USER" |egrep -v grep
pidlist=$(ps -o ppid=$$ | tr '\n' ' '  | sed 's/  /\|/g' | sed 's/ //g')
temp=$(ps -o ppid=$$ | tr '\n' ' ')
parentpid=$(echo $temp | awk '{print $2}')
ps -H aux | egrep -v '(sed|grep|bin)' | egrep '(bash)' | highlight green $parentpid
echo
echo You are: $parentpid | highlight green $parentpid
