#!/bin/bash
# Version=20251009.01
# Search for a PGP key by ID or email address.

for i in "$@" ; do
  if [[ $i == "-V" ]] ; then
     echo  $(basename $0) $Version

     echo "Copyright (C) 2017 Christian Scholz. Alle Rechte vorbehalten."
     echo "Dieses Script ist unter GPL v.2. veröffentlicht"
     echo
     echo "Dieses Script wird unter Ausschluss vom Gewährleistung und Garantie bereitgestellt, soweit dies durch Gesetze ermöglicht wird."
     exit 1
  fi
done

if [ ! -z "$1" ]; then
  gpg --keyserver hkp://keys.gnupg.net --keyserver wwwkeys.pgp.net --search-keys $1
else
  echo "Usage: $0 {Key-ID|E-Mail Address}"
fi
