#!/bin/bash
if grep --quiet ${NAUTILUS_SCRIPT_SELECTED_FILE_PATHS} ~/scripts/backup_configfiles; then
  notify-send "Already existing: [${NAUTILUS_SCRIPT_SELECTED_FILE_PATHS}]"
else
  echo ${NAUTILUS_SCRIPT_SELECTED_FILE_PATHS} >> ~/scripts/backup_configfiles
  notify-send "Added: [${NAUTILUS_SCRIPT_SELECTED_FILE_PATHS}]"
fi
